---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dex-app-k8s.fullname" . }}-postgresql-primary-init-scripts
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "dex-app-k8s.labels" . | nindent 4 }}
data:
  initdb.sql: |
    DROP TABLE IF EXISTS blacklist_ips;
    CREATE TABLE blacklist_ips (
    ip_addr inet PRIMARY KEY,
    blocked_at TIMESTAMP NOT NULL,
    path_requested VARCHAR
    );
