---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dex-app-k8s.fullname" . }}-postgresql
  namespace: {{ .Release.namespace | quote }}
  labels:
    {{- include "dex-app-k8s.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: "b1dub01qWG5ORw=="
  password: "Zmxhc2s="
  replication-password: "R3BmMDEzemd5QQ=="