---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dex-app-k8s.fullname" . }}-postgresql
  namespace: {{ .Release.namespace | quote }}
  labels:
    {{- include "dex-app-k8s.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- define "SecretName" -}} {{ include "dex-app-k8s.fullname" . }}-postgresql {{- end }}
  {{- $secretName := (include "SecretName" .) }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $postgresPass := (get $secretData "postgres-password") | default (randAlphaNum 32 | b64enc) }}
  postgres-password: {{ $postgresPass | quote }}
  {{- $userPass := (get $secretData "user-password") | default (randAlphaNum 32 | b64enc) }}
  user-password: {{ $userPass | quote }}
  {{- $replicationPass := (get $secretData "replication-password") | default (randAlphaNum 32 | b64enc) }}
  replication-password: {{ $replicationPass | quote }}