---
apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-test-postgresql-primary-init-scripts
  namespace: "default"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.6.16
    app.kubernetes.io/instance: psql-test
    app.kubernetes.io/managed-by: Helm
data:
  initdb.sql: |
    DROP TABLE IF EXISTS blacklist_ips;
    CREATE TABLE blacklist_ips (
    ip_addr inet PRIMARY KEY,
    blocked_at TIMESTAMP NOT NULL,
    path_requested VARCHAR
    );
